use solarized::{
    print_fancy,
    VIOLET, BLUE, CYAN, ORANGE,
    WHITE, GREY,
    PrintMode::NewLine,
};

pub fn print_help(_binaryname: String) {
    print_fancy(&[
        ("This program is designed to be a modular web service.\n", CYAN, vec![]),
        ("All paths and routes are configured in config.toml\n", CYAN, vec![]),
        ("If config.toml does not exist, an example project structure can be created.\n\n", CYAN, vec![]),
        ("The ", CYAN, vec![]),
        ("config.toml", VIOLET, vec![]),
        (" file should contain something similar to the following.\n\n", CYAN, vec![]),
//base web config
        ("scope", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("\"localhost\"\n", CYAN, vec![]),
        ("ip", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("\"192.168.1.142\"\n", CYAN, vec![]),
        ("port", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("12345\n", CYAN, vec![]),
//ssl config
        ("ssl_enabled", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("false\n", CYAN, vec![]),
        ("ssl_port", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("44444\n", CYAN, vec![]),
        ("ssl_cert_path", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("\"pems/cert.pem\"\n", CYAN, vec![]),
        ("ssl_key_path", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("\"pems/key.pem\"\n", CYAN, vec![]),
//upload limit
        ("upload_size_limit", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("2147483648", CYAN, vec![]),
        (" # 2 GB (2 * 1024 * 1024 * 1024)\n", GREY, vec![]),
        ("#upload_size_limit = \"disabled\" # allows any size", GREY, vec![]),
        ("upload_storage_limit", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("2147483648\n", CYAN, vec![]),
//browser
        ("browser", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("false\n", CYAN, vec![]),
// slideshow_autoplay
        ("slideshow_autoplay", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("false\n", CYAN, vec![]),       
// slideshow_timer
        ("slideshow_timer", BLUE, vec![]),
        (" = ", WHITE, vec![]),
        ("20\n\n", CYAN, vec![]),
//default routes
        ("[routes]\n", ORANGE, vec![]),
//home route
        ("\"/\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/home.html\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//stuff route
        ("\"/stuff\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/stuff.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/media\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//thumb route
        ("\"/thumb\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/thumb.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/media\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//pdf route
        ("\"/pdf\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/pdf.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/documents\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//downloads route
        ("\"/downloads\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/downloads.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/files\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//playlists route
        ("\"/playlists\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/playlists.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/audio\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//upload route
        ("\"/uplaod\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/upload.html\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//files route
        ("\"/files\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/uploads.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"uploads\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//slideshow route
        ("\"/slideshow\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"slideshow\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/slides\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
//blog route
        ("\"/blog\"", BLUE, vec![]),
        (" = [", WHITE, vec![]),
        ("\"static/blog.html\"", CYAN, vec![]),
        (", ", WHITE, vec![]),
        ("\"static/posts\"", CYAN, vec![]),
        ("]\n", WHITE, vec![]),
    ], NewLine);
    std::process::exit(0);
}
